In [2]:
cat_dog=r"C:\Users\madhu\OneDrive\Documents\Madhu's pri folder\ML_projects\Miniproject_part 2\cat_dogs\PetImages"

In [3]:
# Step 1: Load the dataset
cat_folder = r"C:\Users\madhu\OneDrive\Documents\Madhu's pri folder\ML_projects\Miniproject_part 2\cat_dogs\PetImages\Cat"
dog_folder = r"C:\Users\madhu\OneDrive\Documents\Madhu's pri folder\ML_projects\Miniproject_part 2\cat_dogs\PetImages\Dog"

In [4]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Create an ImageDataGenerator instance for data preprocessing
datagen = ImageDataGenerator(rescale=1./255)  # Normalize pixel values to [0, 1]

# Use the flow_from_directory method to load and resize images
train_generator = datagen.flow_from_directory(
    cat_dog,  # Directory containing subdirectories of 'cats' and 'dogs'
    target_size=(128, 128),  # Resize all images to 128x128
    batch_size=32,
    class_mode='categorical',  # For multi-class classification (cat vs dog)
)


Found 24999 images belonging to 2 classes.


Normalization

In [5]:
#example of single image normalization
import numpy as np
from tensorflow.keras.preprocessing import image
#from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from PIL import Image

# Load an image (replace 'path_to_image.jpg' with your image file path)
img = image.load_img( r"C:\Users\madhu\OneDrive\Documents\Madhu's pri folder\ML_projects\Miniproject_part 2\cat_dogs\PetImages\Cat\0.jpg", target_size=(128, 128))

# Convert to numpy array
img_array = image.img_to_array(img)

# Normalize the pixel values between 0 and 1 (divide by 255)
img_array = img_array / 255.0  # Values now in range [0, 1]

# Alternatively, if you're using a pre-trained model like MobileNetV2
# you can use the preprocess_input function to normalize the image
#img_array = preprocess_input(img_array)  # This handles mean subtraction for MobileNetV2


In [6]:
print(img_array.shape)

(128, 128, 3)


In [7]:
import os
image_files = os.listdir(cat_folder)

# Filter out non-image files if necessary
image_files = [file for file in image_files if file.endswith(('jpg', 'jpeg', 'png', 'gif'))]

# Print the list of image files
print(image_files[0])

0.jpg


In [8]:
def normalize(img):
    img = image.load_img( img, target_size=(128, 128))

# Convert to numpy array
    img_array = image.img_to_array(img)

#Normalize the pixel values between 0 and 1 (divide by 255)
    img_array = img_array / 255.0  # Values now in range [0, 1]
    return img_array

In [ ]:
Multiple image normalization: (cat)

In [10]:
valid_extensions = ('.jpg', '.jpeg', '.png')
cat_images=[]
faults_cat=0
for img_name in os.listdir(cat_folder):
    img_path = os.path.join(cat_folder, img_name)
    try:
        # Normalize the image
        normalized_image = normalize(img_path)
        cat_images.append(normalized_image)
    
    except Exception as e:
        faults_cat=faults_cat+1
        print(f"Error processing {img_name}: {e}")

# Check the result
if cat_images:
    print(cat_images[0])
else:
    print("No valid images were processed.")

Error processing Thumbs.db: cannot identify image file <_io.BytesIO object at 0x00000209AD54EBB0>
[[[0.79607844 0.6431373  0.34117648]
  [0.8156863  0.6627451  0.36078432]
  [0.8235294  0.67058825 0.36862746]
  ...
  [0.9607843  0.8117647  0.49411765]
  [0.95686275 0.79607844 0.4745098 ]
  [0.9372549  0.78431374 0.4745098 ]]

 [[0.79607844 0.6431373  0.34117648]
  [0.8156863  0.6627451  0.36078432]
  [0.8235294  0.67058825 0.36862746]
  ...
  [0.9607843  0.8156863  0.49803922]
  [0.9529412  0.8039216  0.47843137]
  [0.9411765  0.7882353  0.47843137]]

 [[0.79607844 0.6431373  0.34117648]
  [0.8156863  0.6627451  0.36078432]
  [0.8235294  0.67058825 0.36862746]
  ...
  [0.9647059  0.81960785 0.5058824 ]
  [0.9529412  0.80784315 0.49019608]
  [0.94509804 0.7921569  0.48235294]]

 ...

 [[0.62352943 0.4862745  0.21960784]
  [0.6313726  0.49411765 0.22745098]
  [0.6313726  0.49411765 0.22745098]
  ...
  [0.01176471 0.01568628 0.        ]
  [0.01176471 0.01568628 0.        ]
  [0.00784314 0

In [11]:
print(faults_cat)

1


Multiple image normalization: (dog)

In [12]:
dog_images=[]
faults_dog=0
for img_name in os.listdir(dog_folder):
    img_path = os.path.join(dog_folder, img_name)
    try:
        # Normalize the image
        normalized_image = normalize(img_path)
        dog_images.append(normalized_image)
    
    except Exception as e:
        faults_dog=faults_dog+1
        print(f"Error processing {img_name}: {e}")

# Check the result
if dog_images:
    print(dog_images[0])
else:
    print("No valid images were processed.")

Error processing 11702.jpg: cannot identify image file <_io.BytesIO object at 0x00000209AD54EA20>


C:\Users\madhu\anaconda3\Lib\site-packages\PIL\TiffImagePlugin.py:870: UserWarning: Truncated File Read
  warnings.warn(str(msg))


Error processing Thumbs.db: cannot identify image file <_io.BytesIO object at 0x00000209AD9F31A0>
[[[0.45882353 0.4509804  0.49411765]
  [0.42745098 0.41568628 0.48235294]
  [0.44705883 0.4392157  0.49411765]
  ...
  [0.54901963 0.5568628  0.6039216 ]
  [0.52156866 0.5294118  0.5764706 ]
  [0.52156866 0.52156866 0.56078434]]

 [[0.47058824 0.4627451  0.5058824 ]
  [0.44313726 0.43137255 0.49803922]
  [0.45882353 0.4509804  0.5058824 ]
  ...
  [0.5529412  0.56078434 0.60784316]
  [0.5372549  0.54509807 0.5921569 ]
  [0.5372549  0.5372549  0.5764706 ]]

 [[0.48235294 0.4745098  0.5176471 ]
  [0.4509804  0.4392157  0.5058824 ]
  [0.4627451  0.45490196 0.50980395]
  ...
  [0.5568628  0.5647059  0.6117647 ]
  [0.54901963 0.5568628  0.6039216 ]
  [0.54901963 0.56078434 0.59607846]]

 ...

 [[0.23921569 0.30980393 0.3254902 ]
  [0.34117648 0.3529412  0.3882353 ]
  [0.29803923 0.30980393 0.3372549 ]
  ...
  [0.2627451  0.29411766 0.30588236]
  [0.21960784 0.2509804  0.2627451 ]
  [0.2627451  0

In [13]:
print(faults_dog)

2


Preparing data : (training and testing)

In [14]:
import numpy as np

# Assuming `cat_images` and `dog_images` contain normalized images
cat_labels = [0] * len(cat_images)  # Label all cats as 0
dog_labels = [1] * len(dog_images)  # Label all dogs as 1

# Combine images and labels
images = np.array(cat_images + dog_images)  # Combine all images into one array
labels = np.array(cat_labels + dog_labels)  # Combine all labels into one array


In [15]:
from sklearn.model_selection import train_test_split

# Split into training and testing
X_train, X_temp, y_train, y_temp = train_test_split(images, labels, test_size=0.3, random_state=42)

# Further split temp data into validation and test sets
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.33, random_state=42)

print(f"Training data: {X_train.shape}, Validation data: {X_val.shape}, Test data: {X_test.shape}")


Training data: (17498, 128, 128, 3), Validation data: (5025, 128, 128, 3), Test data: (2475, 128, 128, 3)


model preparation

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),  # Input shape should match your normalized images
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),  # Regularization to prevent overfitting
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()


C:\Users\madhu\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 126, 126, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 61, 61, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 57600)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │       7,372,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 7,392,449 (28.20 MB)

 Trainable params: 7,392,449 (28.20 MB)

 Non-trainable params: 0 (0.00 B)

In [18]:
history = model.fit(
    X_train, y_train,
    epochs=5,  # Adjust the number of epochs based on performance
    batch_size=32,
    validation_data=(X_val, y_val)
)

Epoch 1/5
547/547 ━━━━━━━━━━━━━━━━━━━━ 154s 280ms/step - accuracy: 0.7240 - loss: 0.5465 - val_accuracy: 0.7827 - val_loss: 0.4729
Epoch 2/5
547/547 ━━━━━━━━━━━━━━━━━━━━ 147s 269ms/step - accuracy: 0.8015 - loss: 0.4321 - val_accuracy: 0.7733 - val_loss: 0.4763
Epoch 3/5
547/547 ━━━━━━━━━━━━━━━━━━━━ 147s 269ms/step - accuracy: 0.8462 - loss: 0.3588 - val_accuracy: 0.7958 - val_loss: 0.4582
Epoch 4/5
547/547 ━━━━━━━━━━━━━━━━━━━━ 147s 268ms/step - accuracy: 0.8927 - loss: 0.2580 - val_accuracy: 0.7952 - val_loss: 0.4940
Epoch 5/5
547/547 ━━━━━━━━━━━━━━━━━━━━ 146s 267ms/step - accuracy: 0.9384 - loss: 0.1653 - val_accuracy: 0.7940 - val_loss: 0.5522


evaluation

In [19]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")

78/78 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.7940 - loss: 0.5488
Test Accuracy: 80.81%


model upload:

In [21]:
model.save('cat_dog_classifier.keras')

In [22]:
# Replace 'your_directory_path' with the path where you want to save the model
model.save(r"C:\Users\madhu\OneDrive\Documents\Madhu's pri folder\ML_projects\Miniproject_part 2\cat_dogs\cat_dog_classifier.keras")
